config/routes.rb
Rails.application.routes.draw do
  # Define your error handling route using additional_paths
  root 'pages#restricted_home'
  post '/api/chatbot', to: 'chatbot#reply'

  get 'errors/not_found'
  devise_for :patients, controllers: {
    omniauth_callbacks: 'patients/omniauth_callbacks',
    sessions: 'patients/sessions',
    registrations: 'patients/registrations',
    invitations: 'patients/invitations',
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations',
  }
  devise_for :doctors, controllers: {
    sessions: 'doctors/sessions',
    registrations: 'doctors/registrations',
    invitations: 'doctors/invitations',
  }

  authenticated :user, ->(user) { user.doctor? } do
    get '/DoctorPage', to: 'pages#doctorhome', as: :authenticated_doctor_root
  end

  authenticated :user, ->(user) { user.patient? } do
    get '/PatientPage', to: 'pages#patientshome', as: :authenticated_patient_root
  end
  devise_scope :doctor do
    get '/doctors/sign_out', to: 'doctors/sessions#destroy'
  end
  devise_scope :patient do
    get '/patients/sign_out', to: 'patients/sessions#destroy'
  end
  namespace :api do
    namespace :v1 do
      get 'groups/:speciality', to: 'groups#groups_by_speciality'
      post '/send_notifications', to: 'notifications#create'
      get '/get_rndv', to: 'notifications#index'
      get '/get_rndv2', to: 'notifications#index3'
      get '/get_notifications', to: 'notifications#index2'
      delete '/destroy', to: 'notifications#destroy'

      get '/users/:user_id/images/url', to: 'user_images#url'
      get '/doctors_list', to: 'loaddoctors#url'
      post '/user_images', to: 'user_images#create'
      post '/user_images_web', to: 'user_images_web#create'
      get '/patient_data', to: 'patientdata#patient_data'
      get '/doctor_data', to: 'doctordata#doctor_data'
      get '/notification_doctor', to: 'doctordata#notifications'
      post '/experience', to: 'experience#create'
      get '/doctors', to: 'doctorspage#index'



    end
  end
  get 'patient_page', to: 'pages#patientshome'
  get '/patient_page/search_doctors', to: 'pages#patientshome'
  get '/PatientPage/SearchDoctors', to: 'pages#patientssearche'
  get '/PatientPage/FindDoctor', to: 'pages#finddoctor'
  get '/PatientPage/SearchDoctors', to: 'search_doctors#index'

  resource :user_images, only: [:create,:url]

  get '/DoctorPage/appointments', to: 'pages#appointments'
  get '/DoctorPage/PatientList', to: 'pages#patient_list'
  get '/DoctorPage/Account', to: 'pages#Account'


  get '/DoctorPage/Map', to: 'pages#map'
  post '/get_patients', to: 'api#get_patients'
  get '/get_patients/:patient_id', to: 'api#get_patients'
  get '/img/app.png', to: 'custom#redirect_app_image'

  get '(*path)', to: 'application#render_404', constraints: lambda { |req| !req.path.starts_with?('/rails/active_storage') }

end

app/views/shared/_nav.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home</title>


  </head>
 <body>
  <% if current_page?(root_path) %>
<nav id="custom-navbar" class="navbar navbar-expand-lg navbar-light">
  <div class="logo-container" style="display: flex; justify-content: center; align-items: center; width: 50px; height: 50px; border-radius: 50%; overflow: hidden; margin-right: 10px; margin-left: 60px;">
    <%= image_tag('logoo-removebg-preview.png', alt: 'logo', class: 'logo', style: 'max-width: 100%; max-height: 100%;') %>
  </div>
  <%= link_to "Sihati", root_path, class: "navbar-brand text-center", style: "color: #70a5d7;" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  </button>
      <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
              <%= link_to "Contactez-nous","#contacte",class: "nav-link", id: "contact-link",style: "color: black;" %>
          </li>
          <li class="nav-item">
            <%= link_to "Nos-services", "#Nous-services", class: "nav-link" , id: "Nous-services-link",style: "color: black;"%>
          </li>
        </ul>
      </div>


      <div class="secoond">
        <ul class="navbar-nav">
          <button class="connexion-btn12">
<%= link_to "Rejoignez-Nous", "#rejoignez-nous", class: "button-link12", id: "rejoignez-nous-link" %>
          </button>
        </ul>
      </div>

    </nav>
  <% else %>
<nav id="custom-navbar" class="navbar navbar-expand-lg navbar-light">
<div class="logo-container" style="display: flex; justify-content: center; align-items: center; width: 50px; height: 50px; border-radius: 50%; overflow: hidden; margin-right: 10px; margin-left: 10px;">
    <%= image_tag('logo.png', alt: 'logo', class: 'logo', style: 'max-width: 100%; max-height: 100%;') %>
  </div>
  <%= link_to "Sihati", root_path, class: "navbar-brand text-center", style: "color: #70a5d7;" %>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
              <div class="collapse navbar-collapse justify-content-end" id="navbarNav">


        <ul class="navbar-nav">

          <% if current_page?(new_doctor_registration_path)  %>
            <li class="nav-item">
              <%= link_to "Connexion", new_doctor_session_path, class: "nav-link", style: "color: black;" %>
            </li>
          <% elsif current_page?(new_patient_registration_path) %>
            <li class="nav-item">
              <%= link_to "Connexion", new_patient_session_path, class: "nav-link" , style: "color: black;"%>
            </li>
          <% end %>
        </ul>
        </div>
    </nav>
  <% end %>

</body>
</html>

app/views/shared/_upper_nav.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Home</title>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Include Bootstrap CSS -->
  <style>
    body {
      overflow: visible;
    }
  </style>
</head>
<body>
  <% if current_user %>
    <div style="position: absolute; right: 20px; top: 20px;">
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: white; color: black;">
      Se déconnecter
    </button>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
      <% if current_user.role == "patient" %>
        <a class="dropdown-item" href="<%= destroy_patient_session_path %>" data-no-turbolink="true">Deconnexion</a>
      <% elsif current_user.role == "doctor" %>
        <a class="dropdown-item" href="<%= destroy_doctor_session_path %>" data-no-turbolink="true">Deconnexion</a>
      <% end %>
    </div>
  </div>
</div>

    <script>
      document.addEventListener("DOMContentLoaded", function() {
        var dropdownButton = document.getElementById("dropdownMenuButton");
        dropdownButton.addEventListener("click", function() {
          var dropdownMenu = dropdownButton.nextElementSibling;
          if (dropdownMenu.style.display === "block") {
            dropdownMenu.style.display = "none";
          } else {
            dropdownMenu.style.display = "block";
          }
        });
      });
    </script>
  <% end %>

  <!-- Content of your page goes here -->

</body>
</html>